name: podcast_search
description: A library for searching for podcasts, parsing podcast RSS feeds and obtaining episodes details. Supports searching via iTunes and PodcastIndex (preview).

version: 0.5.1
homepage: https://github.com/amugofjava/podcast_search

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  archive: ^3.3.1
  convert: ^3.0.2
  crypto: ^3.0.2
  dio: ^4.0.6
  dart_rss: ^2.0.1
  meta: ^1.8.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.21.4
